### ISSUE TITLE
Enforce value for homepage in sources

### ISSUE THREAD

**Issue by rue-a** [luckinet/ontologics#13]
Each external source should be provided with some form of a (Web)link. If there is not an actual homepage existing, a link to a PDF, paper or any documentation (it could even be the isbn of a book) should be provided at least. It makes not so much sense to link to things that spawn out of thin air.

**Comment by EhrmannS** [comment]
That is true. I would argue however, that there are sources that don't have any representation on the web. I did modify the documentation for https://github.com/luckinet/ontologics/blob/main/R/new_source.R, mentioning this in particular. The point I would like to make is that when using a new source merely as "attribute", it would require slightly different configuration (i.e., not necessarily a homepage).

What I've been thinking though, very similar to your line of thought that for the case where a new source is clearly another vocabulary/ontology of linked data, we need a URL that clearly works...

**Comment by rue-a** [comment]
With adding the `uri_prefix` column to the sources table, and ignoring external sources that don't provide a value for `uri_prefix`, we can close this.
