### ISSUE TITLE
Streamline column names

### ISSUE THREAD

**Issue by rue-a** [luckinet/ontologics#5]
Currently, the column names of the Data.Frames that are part of the `onto` object, are a little mixed up as we see here:

_1. Classes_   
level | class | broader | definition
-|-|-|-

_2. Sources_
sourceID | source_name | description | homepage | license | notes
-|-|-|-|-|-

_3. Concepts_   
code | broader | sourceID
-|-|-

_4. Labels_
code | class | label_en
-|-|-

_5. Mappings_
code | external
-|-

---
I would propose the following changes (the changes include the additional columns in *classes* and *labels* that are mentioned in issue #2 ):

_1. Classes_   
id | label | description | level | has_broader 
-|-|-|-|-

(class -> id, defintion -> description, broader -> has_broader, add label column)

_2. Sources_
id | label | description | homepage | license | notes
-|-|-|-|-|-

(sourceID -> id, source_name -> label)

_3. Concepts_   
id | has_broader | source_id
-|-|-

(code -> id, broader -> has_broader, sourceID -> source_id)

_4. Labels_
id | class | label | description
-|-|-|-

(code -> id, label_en -> label, add description)

_5. Mappings_
id | external_id
-|-

(code -> id, external -> external_id)

Concerning language tags: If we want to add language tags we should also specify this for `description` and `notes`. But generally I think we don't have to, since English is default. If we add other columns for other languages in the future, these can be specified.

Conerning has_broader: I think it is useful to add the `has` here, since it takes away ambiguity (does `broader` mean `is broader` or `has broader`) that could confuse new users of the package, especially if they are not familiar with SKOS.

**Comment by EhrmannS** [comment]
Hi Arne,

thanks for these suggestions. About to implement them; I have two questions.

1. Do you already have an idea on how to implement/handle labels in other languages? I think we need to implement this for sure (at some point), so why not let's prepare it properly right away?! 
2. Shouldn't we use different column names for conceptually different things? I.e., `label` for classes, for sources and for concepts. I would leave them in the upcoming fix as `class_label`, `source_label` and `label_en` (the latter to make sure that this is really supposed to be in english, until we have a better solution for it).

Do you agree with that?

**Comment by rue-a** [comment]
> Hi Arne,
> 
> thanks for these suggestions. About to implement them; I have two questions.
> 
> 1. Do you already have an idea on how to implement/handle labels in other languages? I think we need to implement this for sure (at some point), so why not let's prepare it properly right away?!
> 2. Shouldn't we use different column names for conceptually different things? I.e., `label` for classes, for sources and for concepts. I would leave them in the upcoming fix as `class_label`, `source_label` and `label_en` (the latter to make sure that this is really supposed to be in english, until we have a better solution for it).
> 
> Do you agree with that?

1. I think it would be feasible to add tags in other languages in a separate column as a list that holds strings with a predefined format. Something like: [Deutschland:de, Niemcy:pl, Tyskland:da, ..., {label:lang-tag}].

@. I don't think so, because the conceptual difference is indicated by the Data.Frame names. So if I understand the general use R right, you would always access a column with object@table_name$column_name, e.g. onto@concepts$label or onto@classes$label.

**Comment by EhrmannS** [comment]
I now change the name of the column containing english labels to `label`. I am not the biggest fan of using lists in the column of a table, but we can also solve that in the future. For now, I have implemented all things suggested here.
